version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pendura
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
  php:
    build:
      context: .
      dockerfile: ./Environment/PHP/PHPDockerfile
    container_name: php
    volumes:
      - ./:/var/www/laravel
    entrypoint:
      - php-fpm
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./Environment/NGINX/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/laravel
    links:
      - php
    ports:
      - 80:80
